soignantsaucoeurdesurgences/djazyblog/urls.py
from django.urls import path
from .views import PostDetailView, PostListView, PostShareView, post_search
from .feeds import LatestPostsFeed


app_name = 'blog'


urlpatterns = [
        path('', PostListView.as_view(), name='post_list'),
        path('tag/<slug:tag_slug>/', PostListView.as_view(), name='post_list_by_tag'),

        path(
            '<int:year>/<int:month>/<int:day>/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
        path(
            '<int:year>/<int:month>/<int:day>/<slug:slug>',
            PostDetailView.as_view(),
            {'success': 'success'},
            name='post_detail_com_sent'),

        path('<int:post_id>/share/', PostShareView.as_view(), name='post_share'),
        path(
            '<int:post_id>/share',
            PostShareView.as_view(),
            {'success': 'success'},
            name='post_share_success'),

        path('feed/', LatestPostsFeed(), name='post_feed'),
        path('search/', post_search, name='post_search'),
        ]

soignantsaucoeurdesurgences/djazyblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    """
    custom manager to retrieve post filter by published
    """
    def get_queryset(self):
        return super (PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
            ('draft', 'Draft'),
            ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
            #, unique_for_date='publish')
    author = models.ForeignKey(
            User,
            on_delete=models.CASCADE,
            related_name='blog_post'
            )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
            max_length=10,
            choices=STATUS_CHOICES,
            default='draft'
            )
    objects = models.Manager() # Default manager
    published = PublishedManager() # Custom manager
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
                'blog:post_detail',
                args=[self.publish.year, self.publish.month, self.publish.day, self.slug]
                )


class Comment(models.Model):
    post = models.ForeignKey(
            Post,
            on_delete = models.CASCADE,
            related_name = 'comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

soignantsaucoeurdesurgences/djazyblog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):

    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                                widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

soignantsaucoeurdesurgences/djazyblog/views.py
from django.core.mail import send_mail
#from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models.functions import Greatest
from django.db.models import Count
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import render, get_object_or_404
#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs.get('tag_slug'):
            tag = get_object_or_404(Tag, slug=self.kwargs.get('tag_slug'))
            context['tag'] = tag
            context['posts'] = self.queryset.filter(tags__in=[tag])
        return context


# Display the Post and its 'comments with form'  
class PostDisplay(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post/detail.html'

    def get_object(self):
        return get_object_or_404(
                self.model,
                slug=self.kwargs['slug'],
                status='published',
                publish__year=self.kwargs['year'],
                publish__month=self.kwargs['month'],
                publish__day=self.kwargs['day']
                )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = context['post']
        # List of similar posts
        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(
                tags__in=post_tags_ids
                ).exclude(id=post.id)

        context['similar_posts'] = similar_posts.annotate(
                same_tags=Count('tags')
                ).order_by('-same_tags','-publish')[:4]
        
        context['comment_form'] = CommentForm()
        context['comments'] = post.comments.filter(active=True)
        
        if self.kwargs.get('success'):
            context['sent'] = True
        
        return context


class PostComments(SingleObjectMixin, FormView):
    template_name = 'blog/post/detail.html'
    form_class = CommentForm
    model = Post

    def post(self, request, *args, **kwargs):
        self.object = get_object_or_404(
                self.model,
                slug=self.kwargs['slug'],
                status='published',
                publish__year=self.kwargs['year'],
                publish__month=self.kwargs['month'],
                publish__day=self.kwargs['day']
                )

        self.comment_form = CommentForm(data=request.POST)
        if self.comment_form.is_valid():
            # Create Comment object but don't save to database yet
            self.new_comment = self.comment_form.save(commit=False)
            # Assign the current post to the comment
            self.new_comment.post = self.object
            # Save the comment to the database
            self.new_comment.save()
        else:
            self.comment_form = CommentForm()

        return super().post(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse(
                'blog:post_detail_com_sent',
                kwargs= {
                    'year': self.object.publish.strftime('%Y'),
                    'month': int(self.object.publish.strftime('%m')),
                    'day': int(self.object.publish.strftime('%d')),
                    'slug': self.object.slug,
                    'success': 'success'
                    }
                )


class PostDetailView(View):

    def get(self, request, *args, **kwargs):
        view = PostDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostComments.as_view()
        return view(request, *args, **kwargs)
# End 


class PostShareView(FormView):
    
    template_name = 'blog/post/share.html'
    form_class = EmailPostForm

    def get_success_url(self, **kwargs):
        return reverse("blog:post_share_success", 
                kwargs={'post_id': self.kwargs.get('post_id'), 'success': 'success'}
                )

    def form_valid(self, form):
        post = get_object_or_404(
                Post, 
                id=self.kwargs.get('post_id'),
                status='published'
                )
        post_url = self.request.build_absolute_uri(
                post.get_absolute_url()
                )
        subject = f"{form.cleaned_data['name']} recommends you read " \
                f"{post.title}"
        message = f"Read {post.title} at {post_url}\n\n" \
                f"{form.cleaned_data['name']}\'s comments: {form.cleaned_data['comments']}"
        send_mail(subject, message, 'djazyblog@lhndev.com', [form.cleaned_data['to']])
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PostShareView, self).get_context_data(**kwargs)
        context['post'] = Post.objects.get(id=self.kwargs.get('post_id')
                # get_object_or_404(
                # Post, 
                # id=self.kwargs.get('post_id'),
                # status='published'
                )
        if self.kwargs.get('success'):
            context['sent'] = True
        return context


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # Basic Search in the title & body fiels
            # results = Post.published.annotate(
                    # search=SearchVector('title', 'body'),
                    # ).filter(search=query)

            # Stemming and ranking search results
            # search_vector = SearchVector('title', 'body')
            # search_query = SearchQuery(query)
            # results = Post.published.annotate(
                    # search=search_vector,
                    # rank=SearchRank(search_vector, search_query)
                    # ).filter(search=search_query).order_by('-rank')

            # Stemming and ranking results with weighting queries
            # search_vector = SearchVector('title', weight='A') + \
                            # SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            # results = Post.published.annotate(
                    # search=search_vector,
                    # rank=SearchRank(search_vector, search_query)
                    # ).filter(rank__gte=0.3).order_by('-rank')

            # Searching with trigram similarity
            results = Post.published.annotate(
                    similarity=TrigramSimilarity('title', query),
                    ).filter(similarity__gte=0.1).order_by('-similarity')

            # Searching with trigram similarity in two fiel using Greatest django db function 
            results = Post.published.annotate(
                    similarity=Greatest(
                        TrigramSimilarity('title', query),
                        TrigramSimilarity('body', query)
                    )).filter(similarity__gte=0.1).order_by('-similarity')

    return render(request,
            'blog/post/search.html',
            {
                'form': form,
                'query': query,
                'results': results
                }
            )

soignantsaucoeurdesurgences/djazyblog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load djazyblog_tags %}

{% load i18n %}

{% block title %}{{ post.title }}{% endblock %}

{%block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
  {% blocktranslate trimmed with post_publish=post.publish post_author=post.author%}
    Published {{ post_publish }} by {{ post_author }}
    {% endblocktranslate %}
  </p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      <i class="fas fa-envelope-square"></i>{% translate " Share by e-mail" %}
    </a>
  </p>

  <h2>{% translate "Similar Posts" %}</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    {% translate "There are no similar posts yet" %}
  {% endfor %}

  <!-- Comments -->
  {% with comments.count as total_comments %} 
  <h2>{% blocktranslate trimmed count total_comments=total_comments %}
      {{ total_comments  }} comment
      {% plural %}
      {{ total_comments }} comments
      {% endblocktranslate %}
    </h2>
  {% endwith %}

  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        {% blocktranslate trimmed with forloop_counter=forloop.counter comment_name=comment.name %}
	Comment {{ forloop_counter }} by {{ comment_name }}
	{% endblocktranslate %}
	{{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>{% translate "There is no comment yet." %}</p>
  {% endfor %}

  {% if sent %}
  <h2>{% translate "Your comment has been added and is awaiting validation." %}</h2>
  {% else %}
  <h2>{% translate "Add a new comment" %}</h2>
    <form method='post'>
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="{% translate "Add comment" %}"</p>
    </form>
  {% endif %}

{% endblock %}

soignantsaucoeurdesurgences/djazyblog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

soignantsaucoeurdesurgences/djazyblog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load djazyblog_tags %}
{% load i18n %}


{% block title %}Blog | Soignants Au Cœur Des Urgences{% endblock %}

{% block content %}
  <h1>Soignants Au Cœur Des Urgences</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  
  {% for post in posts %}
    <h2>
      <a href="{{post.get_absolute_url}}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
      Tags:&nbsp;
        {% for tag in post.tags.all %}
	  <a href="{% url "blog:post_list_by_tag" tag.slug %}">
	    {{ tag.name }}
	  </a>
	  {% if not forloop.last %}, {% endif %}
	{% endfor %}
    </p>

    <p class="date">
    {% blocktranslate trimmed with post_publish=post.publish post_author=post.author %}
    Published {{ post_publish }} by {{ post_author }}
    {% endblocktranslate %}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
    <p>
      <a href="{{post.get_absolute_url}}">
	      {% translate "Read more" %}...
      </a>
    </p>
  {% endfor %}
  {% include "blog/pagination.html" with page=page_obj %}
{% endblock %}

soignantsaucoeurdesurgences/djazyblog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load djazyblog_tags %}
{% load i18n %}

{% block title %}{% translate "Search" %}{% endblock %}

{% block content %}
  {% if query %}
    <h1>{% translate "Post containing " %}"{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        {% blocktranslate trimmed count total_results=total_results %}
        Find {{ total_results }} result
	{% plural %}
	Find {{ total_results }} results
        {% endblocktranslate %}
      {% endwith %}
    </h3>
    {% for post in results %}
    <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>{% translate "There are no results for your query." %}</p>
    {% endfor %}
    <p>
      <a href="{% url "blog:post_search" %}">
        <i class="fas fa-search"></i>{% translate " Search again" %}
      </a>
    </p>
  {% else %}
  <h1>{% translate "Search for posts" %}</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="{% translate "Search" %}">
    </form>
  {% endif %}
{% endblock %}

soignantsaucoeurdesurgences/djazyblog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% load i18n %}

{% block title %}{% translate "Share a post" %}{% endblock %}

{% block content %}
  {% if sent %}
    <h1>{% translate "E-mail succesfully sent" %}</h1>
    <p>
      {% blocktranslate trimmed with post_title=post.title form_cleaned_data_to=form.cleaned_data.to %}
      "{{ post_title  }}" was succesfully sent to {{ form_cleaned_data_to }}.
      {% endblocktranslate %}
    </p>
  {% else %}
    <h1>
      {% blocktranslate trimmed with post_title=post.title %}
      Share "{{ post_title }}" by e-mail
      {% endblocktranslate %}
    </h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="{% translate "Envoyer un e-mail" %}">
    </form>
  {% endif %}
{% endblock %}