soignantsaucoeurdesurgences/djazyblog/urls.py
from django.urls import path
from .views import PostDetailView, PostListView, PostShareView, post_search
from .feeds import LatestPostsFeed


app_name = 'blog'


urlpatterns = [
        path('', PostListView.as_view(), name='post_list'),
        path('tag/<slug:tag_slug>/', PostListView.as_view(), name='post_list_by_tag'),

        path(
            '<int:year>/<int:month>/<int:day>/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
        path(
            '<int:year>/<int:month>/<int:day>/<slug:slug>',
            PostDetailView.as_view(),
            {'success': 'success'},
            name='post_detail_com_sent'),

        path('<int:post_id>/share/', PostShareView.as_view(), name='post_share'),
        path(
            '<int:post_id>/share',
            PostShareView.as_view(),
            {'success': 'success'},
            name='post_share_success'),

        path('feed/', LatestPostsFeed(), name='post_feed'),
        path('search/', post_search, name='post_search'),
        ]

soignantsaucoeurdesurgences/djazyblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    """
    custom manager to retrieve post filter by published
    """
    def get_queryset(self):
        return super (PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
            ('draft', 'Draft'),
            ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
            #, unique_for_date='publish')
    author = models.ForeignKey(
            User,
            on_delete=models.CASCADE,
            related_name='blog_post'
            )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
            max_length=10,
            choices=STATUS_CHOICES,
            default='draft'
            )
    objects = models.Manager() # Default manager
    published = PublishedManager() # Custom manager
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
                'blog:post_detail',
                args=[self.publish.year, self.publish.month, self.publish.day, self.slug]
                )


class Comment(models.Model):
    post = models.ForeignKey(
            Post,
            on_delete = models.CASCADE,
            related_name = 'comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

soignantsaucoeurdesurgences/djazyblog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):

    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                                widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

soignantsaucoeurdesurgences/djazyblog/views.py
from django.core.mail import send_mail
#from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models.functions import Greatest
from django.db.models import Count
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import render, get_object_or_404
#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs.get('tag_slug'):
            tag = get_object_or_404(Tag, slug=self.kwargs.get('tag_slug'))
            context['tag'] = tag
            context['posts'] = self.queryset.filter(tags__in=[tag])
        return context


# Display the Post and its 'comments with form'  
class PostDisplay(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post/detail.html'

    def get_object(self):
        return get_object_or_404(
                self.model,
                slug=self.kwargs['slug'],
                status='published',
                publish__year=self.kwargs['year'],
                publish__month=self.kwargs['month'],
                publish__day=self.kwargs['day']
                )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = context['post']
        # List of similar posts
        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(
                tags__in=post_tags_ids
                ).exclude(id=post.id)

        context['similar_posts'] = similar_posts.annotate(
                same_tags=Count('tags')
                ).order_by('-same_tags','-publish')[:4]
        
        context['comment_form'] = CommentForm()
        context['comments'] = post.comments.filter(active=True)
        
        if self.kwargs.get('success'):
            context['sent'] = True
        
        return context


class PostComments(SingleObjectMixin, FormView):
    template_name = 'blog/post/detail.html'
    form_class = CommentForm
    model = Post

    def post(self, request, *args, **kwargs):
        self.object = get_object_or_404(
                self.model,
                slug=self.kwargs['slug'],
                status='published',
                publish__year=self.kwargs['year'],
                publish__month=self.kwargs['month'],
                publish__day=self.kwargs['day']
                )

        self.comment_form = CommentForm(data=request.POST)
        if self.comment_form.is_valid():
            # Create Comment object but don't save to database yet
            self.new_comment = self.comment_form.save(commit=False)
            # Assign the current post to the comment
            self.new_comment.post = self.object
            # Save the comment to the database
            self.new_comment.save()
        else:
            self.comment_form = CommentForm()

        return super().post(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse(
                'blog:post_detail_com_sent',
                kwargs= {
                    'year': self.object.publish.strftime('%Y'),
                    'month': int(self.object.publish.strftime('%m')),
                    'day': int(self.object.publish.strftime('%d')),
                    'slug': self.object.slug,
                    'success': 'success'
                    }
                )


class PostDetailView(View):

    def get(self, request, *args, **kwargs):
        view = PostDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostComments.as_view()
        return view(request, *args, **kwargs)
# End 


class PostShareView(FormView):
    
    template_name = 'blog/post/share.html'
    form_class = EmailPostForm

    def get_success_url(self, **kwargs):
        return reverse("blog:post_share_success", 
                kwargs={'post_id': self.kwargs.get('post_id'), 'success': 'success'}
                )

    def form_valid(self, form):
        post = get_object_or_404(
                Post, 
                id=self.kwargs.get('post_id'),
                status='published'
                )
        post_url = self.request.build_absolute_uri(
                post.get_absolute_url()
                )
        subject = f"{form.cleaned_data['name']} recommends you read " \
                f"{post.title}"
        message = f"Read {post.title} at {post_url}\n\n" \
                f"{form.cleaned_data['name']}\'s comments: {form.cleaned_data['comments']}"
        send_mail(subject, message, 'djazyblog@lhndev.com', [form.cleaned_data['to']])
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PostShareView, self).get_context_data(**kwargs)
        context['post'] = Post.objects.get(id=self.kwargs.get('post_id')
                # get_object_or_404(
                # Post, 
                # id=self.kwargs.get('post_id'),
                # status='published'
                )
        if self.kwargs.get('success'):
            context['sent'] = True
        return context


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # Basic Search in the title & body fiels
            # results = Post.published.annotate(
                    # search=SearchVector('title', 'body'),
                    # ).filter(search=query)

            # Stemming and ranking search results
            # search_vector = SearchVector('title', 'body')
            # search_query = SearchQuery(query)
            # results = Post.published.annotate(
                    # search=search_vector,
                    # rank=SearchRank(search_vector, search_query)
                    # ).filter(search=search_query).order_by('-rank')

            # Stemming and ranking results with weighting queries
            # search_vector = SearchVector('title', weight='A') + \
                            # SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            # results = Post.published.annotate(
                    # search=search_vector,
                    # rank=SearchRank(search_vector, search_query)
                    # ).filter(rank__gte=0.3).order_by('-rank')

            # Searching with trigram similarity
            results = Post.published.annotate(
                    similarity=TrigramSimilarity('title', query),
                    ).filter(similarity__gte=0.1).order_by('-similarity')

            # Searching with trigram similarity in two fiel using Greatest django db function 
            results = Post.published.annotate(
                    similarity=Greatest(
                        TrigramSimilarity('title', query),
                        TrigramSimilarity('body', query)
                    )).filter(similarity__gte=0.1).order_by('-similarity')

    return render(request,
            'blog/post/search.html',
            {
                'form': form,
                'query': query,
                'results': results
                }
            )

soignantsaucoeurdesurgences/djazyblog/templates/blog/base.html
{% load djazyblog_tags %}
{% load static %}
{% load i18n %}
{% total_posts as total_posts %}

<!DOCSTYLE html>
  <html class="has-navbar-fixed-top">

    <head>
      <meta charset="utf-8">
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>{% block title %}{% endblock %}</title>
      <!-- favicon -->
      <link rel="apple-touch-icon" sizes="76x76" href="{% static "apple-touch-icon.png" %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static "favicon-32x32.png" %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static "favicon-16x16.png" %}">
      <link rel="manifest" href="{% static "site.webmanifest" %}">
      <link rel="mask-icon" href="{% static "safari-pinned-tab.svg" %}" color="#5bbad5">
      <meta name="msapplication-TileColor" content="#da532c">
      <meta name="theme-color" content="#ffffff">
      <!-- end favicon -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
      <style type="text/css">
        .footer {
          padding: 1.5rem 1.5rem 1.5rem;
        } 
      </style>

      <script src="https://kit.fontawesome.com/2f3d485025.js" crossorigin="anonymous"></script>
    </head>
    <body>
      
      <header>
        {% block navbar %}
          {% include "blog/navbar.html" %}
        {%  endblock %}
      </header>

      <div id="content" class="columns is-centered">
	<div class="column is-four-fifths">
	  <div class="box">
	  <div class="content">
          {% block content %}{% endblock %}
	  </div>
	  </div>
        </div>
	
	<div id="sidebar" class="column ">
	  <div class="box has-background-grey-light">
	    <div class="content">
	      <h2><a href="{% url 'blog:post_list' %}">Soignants Au Cœur Des Urgences</a></h2>
	      <p>
	        Blog de l'association <em>Soignants Au Cœur Des Urgences</em>.
	      </p>
	      <p>
	      {% blocktranslate trimmed count total_posts=total_posts %}
                We published {{ total_posts }} post so far.
                {% plural %}
		We published {{ total_posts }} posts so far.
	        {% endblocktranslate %}
	      </p>
              <p>
	        <a href="{% url "blog:post_feed" %}">
	          <i class="fas fa-rss-square"></i>{% translate " Suscribe to our RSS feed" %}
	        </a>
	      </p>
	      <p>
	        <a href={% url "blog:post_search" %}>
		  <i class="fas fa-search"></i>{% translate " Search a post" %}
		</a>
	      </p>

	      <h3>{% translate "Latest posts" %}</h3>
	      {% show_latest_posts 3 %}
	      <h3>{% translate "Most commented posts" %}</h3>
	      {% get_most_commented_posts as most_commented_posts %}
	      <ul>
	        {% for post in most_commented_posts %}
	          <li>
	            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
	          </li>
	        {% endfor %}
	      </div>
	    </div>
          </div>
        </div>

      {% block footer %}
      <footer class="footer has-background-grey-light">
        <div class="content has-text-centered">
          <strong>Soignants au Coeur des Urgences</strong>
	  hosted and developed with <i class="fas fa-heart"></i> 
	  by <a href="https:www.lhndev.com">LHnDEV</a>
        </div>
      </footer>
      {% endblock %}

      {% block footer_javascript %}{% endblock %}

    </body>
  </html>

soignantsaucoeurdesurgences/djazyblog/templates/blog/navbar.html
{% load static %}
{% load i18n %}

<nav class="navbar is-info is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="">
      <img src="{% static "img/logo.png" %}" alt="Logo">&nbsp;Soignants Au Coeur Des Urgences
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasic">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasic" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item"  href="{% url 'blog:post_list' %}">
        Blog
      </a>
      <a class="navbar-item" href="">
	Forum
      </a>
    </div>

    <div class="navbar-end">
      <a class="navbar-item" href="">
	{% translate "Log In" %}
      </a>
      <a class="navbar-item" href="">
	{% translate "Register" %}
      </a>
    </div>
  </div>
</nav>



{% block footer_javascript %}
<script>
document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>
{% endblock %}

soignantsaucoeurdesurgences/djazyblog/templates/blog/pagination.html
{% load i18n %}
<nav class="pagination" role="navigation" aria-label="pagination">

  <div class="pagination-list">
    <span class="pagination-ellipsis">Page</span>
      
    <a class="pagination-link is-current" aria-label="{{ page.number }}" aria-current="page">
      {{ page.number }}
    </a>

    <span class="pagination-ellipsis">{% translate "on a total of " %} {{ page.paginator.num_pages }}.</span>
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}" class="pagination-previous">{% translate "Previous" %}</a>
    {% endif %}
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}" class="pagination-next">{% translate "Next" %}</a>
    {% endif %}
  </div>
</nav>